# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X6Qz7FVPFER983KlPYm6cpwYndQ--hsy
"""



import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files
uploaded = files.upload()

from google.colab import files

uploaded = files.upload("superstore_dataset.zip.csv")

from google.colab import files

uploaded = files.upload("superstore.csv")

import pandas as pd

df = pd.read_csv("superstore.csv.zip")

df.head()

import os

print(os.listdir())

import pandas as pd

# Load dataset
df = pd.read_csv("superstore.csv", encoding="latin1")

# Show first 5 rows
df.head()

import os

print(os.listdir())

!rm -r superstore.csv





from google.colab import files

uploaded = files.upload()

import os

print(os.listdir())

!rm -r superstore.csv

!rm superstore_dataset.zip.csv

from google.colab import files

uploaded = files.upload()

!rm -r superstore.csv

!rm superstore_dataset.zip.csv

from google.colab import files

uploaded = files.upload()

!rm -r superstore.csv

!rm superstore_dataset.zip.csv

from google.colab import files

uploaded = files.upload()

import os

print(os.listdir())

import pandas as pd

df = pd.read_csv("Sample - Superstore.csv", encoding="latin1")

df.head()

df.isnull().sum()

df.info()

df.isnull().sum()

df.drop_duplicates(inplace=True)

df['Order Date'] = pd.to_datetime(df['Order Date'], errors='coerce')

df['Order Date'].isnull().sum()

df['Month'] = df['Order Date'].dt.month_name()

top_products = df.groupby('Sub-Category')['Sales'].sum().sort_values(ascending=False).head(10)

top_products.plot(kind='bar', figsize=(10,5))
plt.title("Top Selling Products")
plt.xlabel("Product")
plt.ylabel("Sales")
plt.show()

profit = df.groupby('Category')['Profit'].sum()

profit.plot(kind='pie', autopct='%1.1f%%', figsize=(7,7))
plt.title("Profit Analysis")
plt.ylabel("")
plt.show()

region_sales = df.groupby('Region')['Sales'].sum()

region_sales.plot(kind='bar')
plt.title("Region-wise Sales")
plt.show()

"""1. West region generated highest sales.
2. Technology category produced highest profit.
3. Sales increased during November and December.
4. High discounts reduced profits.
"""